# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ltMB6WygoSBIoPPnSdcKBrAp_29cRo-
"""

#pip install plotly
#pip install plotly pandas

#pip install streamlit

import streamlit as st

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Create a Streamlit app title
st.title('Largest Companies Visualization')

# Load the dataset (assuming 'Largest_Companies.csv' is in your Colab environment)
largest_companies = pd.read_csv('Largest_Companies.csv')

# Cleaning the Dataset (you can use your existing code)
missing_values = largest_companies.isnull().sum()
largest_companies.dropna(inplace=True)
duplicate_rows = largest_companies.duplicated()
largest_companies.drop_duplicates(keep='first', inplace=True)
largest_companies['Revenue (USD millions)'] = largest_companies['Revenue (USD millions)'].str.replace(',', '').astype(float)

# Creating a Mini Dataframe for visualizations
top_10_revenue = largest_companies.sort_values(by='Revenue (USD millions)', ascending=False).head(10)

# Visualization 3: Pie Chart of Distribution of Companies Over Industries
industry_distribution = largest_companies['Industry'].value_counts().reset_index()
industry_distribution.columns = ['Industry', 'Count']

st.header('Distribution of Companies Over Industries (Pie Chart)')
fig = px.pie(industry_distribution, names='Industry', values='Count',
             title='Distribution of Companies Over Industries')
st.plotly_chart(fig)

# Visualization 4: Barplot of Distribution of Revenue Growth
st.header('Distribution of Revenue Growth')
st.plotly_chart(px.box(largest_companies, y='Revenue growth', title='Distribution of Revenue Growth'))

# Visualization 5: Treemap of Revenue Distribution by Industry
st.header('Revenue Distribution by Industry (Treemap)')
st.plotly_chart(px.treemap(largest_companies,
                  path=['Industry', 'Name'],
                  values='Revenue (USD millions)',
                  title='Revenue Distribution by Industry (Treemap)'))